services:
  scau_jwc:  # 定义一个名为 scau_jwc 的服务
    image: scau_jwc_v1  # 指定镜像名
    build:
      context: .  # 指定构建上下文为当前目录
      dockerfile: Dockerfile  # 使用当前目录下的 Dockerfile 文件进行构建
    ports:
      - "8000:8000"  # 将容器的 8000 端口映射到主机的 8000 端口
    volumes:
      - C:\xudawu\DockerData2024_09_29\scau_jwc_2024_11_01:/scau_jwc/data  # 将主机目录挂载到容器内的数据目录
    restart: always  # 设置容器在失败后自动重启
